#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Tue Nov 19 19:38:42 2019
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from Main import Main


class Simulti(wx.App):
    def OnInit(self):
        self.main = Main(None, wx.ID_ANY, "")
        self.SetTopWindow(self.main)
        self.main.Show()
        return True

# end of class Simulti

if __name__ == "__main__":
    Simulti = Simulti(0)
    Simulti.MainLoop()
